name: fontesio-services
services:
  database:
    image: postgres:16
    container_name: database
    environment:
      - POSTGRES_USER=fontesio
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fontesio
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: