name: Assign Vercel Preview Domain

on:
  deployment_status:

jobs:
  Assign-Domain:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Update Vercel preview domain
        run: vercel alias set ${{ github.event.deployment_status.target_url }} preview.fontesio.com --token=${{ secrets.VERCEL_TOKEN }}
